### PR TITLE
RTL support and more

### LINKED ISSUE #9: support for RTL tables
Please add support for tables with "direction:trl" style.

### PR DESCRIPTION
**Pull request by YehudahA**
fix #9 
and #11

### CODE REVIEW

**Review by smasala — APPROVED** [review]

**Comment by smasala** [comment]
Thank you for your PR

**Comment by smasala** [comment]
@YehudahA Sorry, I had to revert the changes https://github.com/smasala/ColResize/pull/15. Other than that one issue it looks great 👍 Fixes https://github.com/smasala/ColResize/issues/11 really well!

Maybe it would also be good if the examples in `docs/index.html` were updated accordingly showing a table with `rtl` support. Thanks again.

**Comment by smasala** [comment]
@YehudahA any update on this?

**Comment by YehudahA** [comment]
I hope soon I will have the time for it.

**Pull request merged**
